export interface UKLocation {
  slug: string
  name: string
  region: string
  nearestCity: string
}

export const ukLocations: UKLocation[] = [

  // ── YORKSHIRE (existing) ────────────────────────────────────────────────
  { slug: "leeds",                name: "Leeds",              region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "bradford",             name: "Bradford",           region: "West Yorkshire",    nearestCity: "Bradford" },
  { slug: "wakefield",            name: "Wakefield",          region: "West Yorkshire",    nearestCity: "Wakefield" },
  { slug: "huddersfield",         name: "Huddersfield",       region: "West Yorkshire",    nearestCity: "Huddersfield" },
  { slug: "halifax",              name: "Halifax",            region: "West Yorkshire",    nearestCity: "Halifax" },
  { slug: "pontefract",           name: "Pontefract",         region: "West Yorkshire",    nearestCity: "Wakefield" },
  { slug: "normanton",            name: "Normanton",          region: "West Yorkshire",    nearestCity: "Wakefield" },
  { slug: "castleford",           name: "Castleford",         region: "West Yorkshire",    nearestCity: "Wakefield" },
  { slug: "dewsbury",             name: "Dewsbury",           region: "West Yorkshire",    nearestCity: "Huddersfield" },
  { slug: "batley",               name: "Batley",             region: "West Yorkshire",    nearestCity: "Huddersfield" },
  { slug: "morley",               name: "Morley",             region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "ossett",               name: "Ossett",             region: "West Yorkshire",    nearestCity: "Wakefield" },
  { slug: "horsforth",            name: "Horsforth",          region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "keighley",             name: "Keighley",           region: "West Yorkshire",    nearestCity: "Bradford" },
  { slug: "bingley",              name: "Bingley",            region: "West Yorkshire",    nearestCity: "Bradford" },
  { slug: "shipley",              name: "Shipley",            region: "West Yorkshire",    nearestCity: "Bradford" },
  { slug: "otley",                name: "Otley",              region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "ilkley",               name: "Ilkley",             region: "West Yorkshire",    nearestCity: "Bradford" },
  { slug: "wetherby",             name: "Wetherby",           region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "garforth",             name: "Garforth",           region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "pudsey",               name: "Pudsey",             region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "rothwell",             name: "Rothwell",           region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "brighouse",            name: "Brighouse",          region: "West Yorkshire",    nearestCity: "Halifax" },
  { slug: "elland",               name: "Elland",             region: "West Yorkshire",    nearestCity: "Halifax" },
  { slug: "sowerby-bridge",       name: "Sowerby Bridge",     region: "West Yorkshire",    nearestCity: "Halifax" },
  { slug: "todmorden",            name: "Todmorden",          region: "West Yorkshire",    nearestCity: "Halifax" },
  { slug: "hebden-bridge",        name: "Hebden Bridge",      region: "West Yorkshire",    nearestCity: "Halifax" },
  { slug: "featherstone",         name: "Featherstone",       region: "West Yorkshire",    nearestCity: "Wakefield" },
  { slug: "knottingley",          name: "Knottingley",        region: "West Yorkshire",    nearestCity: "Wakefield" },
  { slug: "hemsworth",            name: "Hemsworth",          region: "West Yorkshire",    nearestCity: "Wakefield" },
  { slug: "cleckheaton",          name: "Cleckheaton",        region: "West Yorkshire",    nearestCity: "Bradford" },
  { slug: "heckmondwike",         name: "Heckmondwike",       region: "West Yorkshire",    nearestCity: "Huddersfield" },
  { slug: "mirfield",             name: "Mirfield",           region: "West Yorkshire",    nearestCity: "Huddersfield" },
  { slug: "liversedge",           name: "Liversedge",         region: "West Yorkshire",    nearestCity: "Bradford" },
  { slug: "yeadon",               name: "Yeadon",             region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "guiseley",             name: "Guiseley",           region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "rawdon",               name: "Rawdon",             region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "farsley",              name: "Farsley",            region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "armley",               name: "Armley",             region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "beeston",              name: "Beeston",            region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "seacroft",             name: "Seacroft",           region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "headingley",           name: "Headingley",         region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "roundhay",             name: "Roundhay",           region: "West Yorkshire",    nearestCity: "Leeds" },
  { slug: "sheffield",            name: "Sheffield",          region: "South Yorkshire",   nearestCity: "Sheffield" },
  { slug: "rotherham",            name: "Rotherham",          region: "South Yorkshire",   nearestCity: "Sheffield" },
  { slug: "barnsley",             name: "Barnsley",           region: "South Yorkshire",   nearestCity: "Barnsley" },
  { slug: "doncaster",            name: "Doncaster",          region: "South Yorkshire",   nearestCity: "Doncaster" },
  { slug: "mexborough",           name: "Mexborough",         region: "South Yorkshire",   nearestCity: "Rotherham" },
  { slug: "rawmarsh",             name: "Rawmarsh",           region: "South Yorkshire",   nearestCity: "Rotherham" },
  { slug: "maltby",               name: "Maltby",             region: "South Yorkshire",   nearestCity: "Rotherham" },
  { slug: "penistone",            name: "Penistone",          region: "South Yorkshire",   nearestCity: "Barnsley" },
  { slug: "stocksbridge",         name: "Stocksbridge",       region: "South Yorkshire",   nearestCity: "Sheffield" },
  { slug: "wath-upon-dearne",     name: "Wath-upon-Dearne",   region: "South Yorkshire",   nearestCity: "Rotherham" },
  { slug: "conisbrough",          name: "Conisbrough",        region: "South Yorkshire",   nearestCity: "Doncaster" },
  { slug: "armthorpe",            name: "Armthorpe",          region: "South Yorkshire",   nearestCity: "Doncaster" },
  { slug: "bentley",              name: "Bentley",            region: "South Yorkshire",   nearestCity: "Doncaster" },
  { slug: "york",                 name: "York",               region: "North Yorkshire",   nearestCity: "York" },
  { slug: "harrogate",            name: "Harrogate",          region: "North Yorkshire",   nearestCity: "Harrogate" },
  { slug: "scarborough",          name: "Scarborough",        region: "North Yorkshire",   nearestCity: "Scarborough" },
  { slug: "northallerton",        name: "Northallerton",      region: "North Yorkshire",   nearestCity: "Northallerton" },
  { slug: "ripon",                name: "Ripon",              region: "North Yorkshire",   nearestCity: "Harrogate" },
  { slug: "skipton",              name: "Skipton",            region: "North Yorkshire",   nearestCity: "Skipton" },
  { slug: "whitby",               name: "Whitby",             region: "North Yorkshire",   nearestCity: "Scarborough" },
  { slug: "knaresborough",        name: "Knaresborough",      region: "North Yorkshire",   nearestCity: "Harrogate" },
  { slug: "selby",                name: "Selby",              region: "North Yorkshire",   nearestCity: "York" },
  { slug: "tadcaster",            name: "Tadcaster",          region: "North Yorkshire",   nearestCity: "York" },
  { slug: "malton",               name: "Malton",             region: "North Yorkshire",   nearestCity: "York" },
  { slug: "filey",                name: "Filey",              region: "North Yorkshire",   nearestCity: "Scarborough" },
  { slug: "settle",               name: "Settle",             region: "North Yorkshire",   nearestCity: "Skipton" },
  { slug: "hull",                 name: "Hull",               region: "East Yorkshire",    nearestCity: "Hull" },
  { slug: "beverley",             name: "Beverley",           region: "East Yorkshire",    nearestCity: "Hull" },
  { slug: "bridlington",          name: "Bridlington",        region: "East Yorkshire",    nearestCity: "Hull" },
  { slug: "driffield",            name: "Driffield",          region: "East Yorkshire",    nearestCity: "Hull" },
  { slug: "goole",                name: "Goole",              region: "East Yorkshire",    nearestCity: "Hull" },
  { slug: "pocklington",          name: "Pocklington",        region: "East Yorkshire",    nearestCity: "York" },
  { slug: "hessle",               name: "Hessle",             region: "East Yorkshire",    nearestCity: "Hull" },
  { slug: "cottingham",           name: "Cottingham",         region: "East Yorkshire",    nearestCity: "Hull" },
  { slug: "brough",               name: "Brough",             region: "East Yorkshire",    nearestCity: "Hull" },
  { slug: "howden",               name: "Howden",             region: "East Yorkshire",    nearestCity: "Goole" },

  // ── NORTH WEST ENGLAND ──────────────────────────────────────────────────
  { slug: "manchester",           name: "Manchester",         region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "salford",              name: "Salford",            region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "stockport",            name: "Stockport",          region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "bolton",               name: "Bolton",             region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "bury",                 name: "Bury",               region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "rochdale",             name: "Rochdale",           region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "oldham",               name: "Oldham",             region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "wigan",                name: "Wigan",              region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "leigh",                name: "Leigh",              region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "ashton-under-lyne",    name: "Ashton-under-Lyne",  region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "altrincham",           name: "Altrincham",         region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "stretford",            name: "Stretford",          region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "sale",                 name: "Sale",               region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "eccles",               name: "Eccles",             region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "didsbury",             name: "Didsbury",           region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "chorlton",             name: "Chorlton",           region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "fallowfield",          name: "Fallowfield",        region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "moss-side",            name: "Moss Side",          region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "ancoats",              name: "Ancoats",            region: "Greater Manchester", nearestCity: "Manchester" },
  { slug: "liverpool",            name: "Liverpool",          region: "Merseyside",         nearestCity: "Liverpool" },
  { slug: "birkenhead",           name: "Birkenhead",         region: "Merseyside",         nearestCity: "Liverpool" },
  { slug: "wallasey",             name: "Wallasey",           region: "Merseyside",         nearestCity: "Liverpool" },
  { slug: "southport",            name: "Southport",          region: "Merseyside",         nearestCity: "Liverpool" },
  { slug: "st-helens",            name: "St Helens",          region: "Merseyside",         nearestCity: "Liverpool" },
  { slug: "warrington",           name: "Warrington",         region: "Cheshire",           nearestCity: "Manchester" },
  { slug: "runcorn",              name: "Runcorn",            region: "Cheshire",           nearestCity: "Liverpool" },
  { slug: "widnes",               name: "Widnes",             region: "Cheshire",           nearestCity: "Liverpool" },
  { slug: "chester",              name: "Chester",            region: "Cheshire",           nearestCity: "Chester" },
  { slug: "crewe",                name: "Crewe",              region: "Cheshire",           nearestCity: "Chester" },
  { slug: "macclesfield",         name: "Macclesfield",       region: "Cheshire",           nearestCity: "Manchester" },
  { slug: "ellesmere-port",       name: "Ellesmere Port",     region: "Cheshire",           nearestCity: "Chester" },
  { slug: "nantwich",             name: "Nantwich",           region: "Cheshire",           nearestCity: "Chester" },
  { slug: "congleton",            name: "Congleton",          region: "Cheshire",           nearestCity: "Manchester" },
  { slug: "wilmslow",             name: "Wilmslow",           region: "Cheshire",           nearestCity: "Manchester" },
  { slug: "knutsford",            name: "Knutsford",          region: "Cheshire",           nearestCity: "Manchester" },
  { slug: "preston",              name: "Preston",            region: "Lancashire",         nearestCity: "Preston" },
  { slug: "blackpool",            name: "Blackpool",          region: "Lancashire",         nearestCity: "Blackpool" },
  { slug: "blackburn",            name: "Blackburn",          region: "Lancashire",         nearestCity: "Blackburn" },
  { slug: "burnley",              name: "Burnley",            region: "Lancashire",         nearestCity: "Burnley" },
  { slug: "accrington",           name: "Accrington",         region: "Lancashire",         nearestCity: "Blackburn" },
  { slug: "lancaster",            name: "Lancaster",          region: "Lancashire",         nearestCity: "Lancaster" },
  { slug: "chorley",              name: "Chorley",            region: "Lancashire",         nearestCity: "Preston" },
  { slug: "nelson",               name: "Nelson",             region: "Lancashire",         nearestCity: "Burnley" },
  { slug: "lytham-st-annes",      name: "Lytham St Annes",    region: "Lancashire",         nearestCity: "Blackpool" },
  { slug: "morecambe",            name: "Morecambe",          region: "Lancashire",         nearestCity: "Lancaster" },
  { slug: "fleetwood",            name: "Fleetwood",          region: "Lancashire",         nearestCity: "Blackpool" },
  { slug: "clitheroe",            name: "Clitheroe",          region: "Lancashire",         nearestCity: "Blackburn" },
  { slug: "carlisle",             name: "Carlisle",           region: "Cumbria",            nearestCity: "Carlisle" },
  { slug: "barrow-in-furness",    name: "Barrow-in-Furness",  region: "Cumbria",            nearestCity: "Barrow-in-Furness" },
  { slug: "kendal",               name: "Kendal",             region: "Cumbria",            nearestCity: "Lancaster" },
  { slug: "workington",           name: "Workington",         region: "Cumbria",            nearestCity: "Carlisle" },
  { slug: "whitehaven",           name: "Whitehaven",         region: "Cumbria",            nearestCity: "Carlisle" },
  { slug: "penrith",              name: "Penrith",            region: "Cumbria",            nearestCity: "Carlisle" },

  // ── NORTH EAST ENGLAND ──────────────────────────────────────────────────
  { slug: "newcastle-upon-tyne",  name: "Newcastle upon Tyne", region: "Tyne and Wear",    nearestCity: "Newcastle" },
  { slug: "gateshead",            name: "Gateshead",          region: "Tyne and Wear",      nearestCity: "Newcastle" },
  { slug: "sunderland",           name: "Sunderland",         region: "Tyne and Wear",      nearestCity: "Sunderland" },
  { slug: "south-shields",        name: "South Shields",      region: "Tyne and Wear",      nearestCity: "Newcastle" },
  { slug: "tynemouth",            name: "Tynemouth",          region: "Tyne and Wear",      nearestCity: "Newcastle" },
  { slug: "whitley-bay",          name: "Whitley Bay",        region: "Tyne and Wear",      nearestCity: "Newcastle" },
  { slug: "jarrow",               name: "Jarrow",             region: "Tyne and Wear",      nearestCity: "Newcastle" },
  { slug: "washington",           name: "Washington",         region: "Tyne and Wear",      nearestCity: "Sunderland" },
  { slug: "durham",               name: "Durham",             region: "County Durham",      nearestCity: "Durham" },
  { slug: "darlington",           name: "Darlington",         region: "County Durham",      nearestCity: "Darlington" },
  { slug: "bishop-auckland",      name: "Bishop Auckland",    region: "County Durham",      nearestCity: "Durham" },
  { slug: "chester-le-street",    name: "Chester-le-Street",  region: "County Durham",      nearestCity: "Durham" },
  { slug: "consett",              name: "Consett",            region: "County Durham",      nearestCity: "Durham" },
  { slug: "stanley",              name: "Stanley",            region: "County Durham",      nearestCity: "Durham" },
  { slug: "newton-aycliffe",      name: "Newton Aycliffe",    region: "County Durham",      nearestCity: "Darlington" },
  { slug: "peterlee",             name: "Peterlee",           region: "County Durham",      nearestCity: "Sunderland" },
  { slug: "seaham",               name: "Seaham",             region: "County Durham",      nearestCity: "Sunderland" },
  { slug: "middlesbrough",        name: "Middlesbrough",      region: "Teesside",           nearestCity: "Middlesbrough" },
  { slug: "stockton-on-tees",     name: "Stockton-on-Tees",   region: "Teesside",           nearestCity: "Middlesbrough" },
  { slug: "hartlepool",           name: "Hartlepool",         region: "Teesside",           nearestCity: "Middlesbrough" },
  { slug: "redcar",               name: "Redcar",             region: "Teesside",           nearestCity: "Middlesbrough" },
  { slug: "billingham",           name: "Billingham",         region: "Teesside",           nearestCity: "Middlesbrough" },
  { slug: "thornaby",             name: "Thornaby",           region: "Teesside",           nearestCity: "Middlesbrough" },
  { slug: "hexham",               name: "Hexham",             region: "Northumberland",     nearestCity: "Newcastle" },
  { slug: "ashington",            name: "Ashington",          region: "Northumberland",     nearestCity: "Newcastle" },
  { slug: "blyth",                name: "Blyth",              region: "Northumberland",     nearestCity: "Newcastle" },
  { slug: "morpeth",              name: "Morpeth",            region: "Northumberland",     nearestCity: "Newcastle" },
  { slug: "alnwick",              name: "Alnwick",            region: "Northumberland",     nearestCity: "Newcastle" },

  // ── EAST MIDLANDS ───────────────────────────────────────────────────────
  { slug: "nottingham",           name: "Nottingham",         region: "East Midlands",      nearestCity: "Nottingham" },
  { slug: "derby",                name: "Derby",              region: "East Midlands",      nearestCity: "Derby" },
  { slug: "leicester",            name: "Leicester",          region: "East Midlands",      nearestCity: "Leicester" },
  { slug: "lincoln",              name: "Lincoln",            region: "East Midlands",      nearestCity: "Lincoln" },
  { slug: "northampton",          name: "Northampton",        region: "East Midlands",      nearestCity: "Northampton" },
  { slug: "kettering",            name: "Kettering",          region: "East Midlands",      nearestCity: "Northampton" },
  { slug: "corby",                name: "Corby",              region: "East Midlands",      nearestCity: "Northampton" },
  { slug: "loughborough",         name: "Loughborough",       region: "East Midlands",      nearestCity: "Leicester" },
  { slug: "mansfield",            name: "Mansfield",          region: "East Midlands",      nearestCity: "Nottingham" },
  { slug: "chesterfield",         name: "Chesterfield",       region: "East Midlands",      nearestCity: "Sheffield" },
  { slug: "ilkeston",             name: "Ilkeston",           region: "East Midlands",      nearestCity: "Nottingham" },
  { slug: "long-eaton",           name: "Long Eaton",         region: "East Midlands",      nearestCity: "Nottingham" },
  { slug: "hucknall",             name: "Hucknall",           region: "East Midlands",      nearestCity: "Nottingham" },
  { slug: "kirkby-in-ashfield",   name: "Kirkby-in-Ashfield", region: "East Midlands",      nearestCity: "Nottingham" },
  { slug: "sutton-in-ashfield",   name: "Sutton-in-Ashfield", region: "East Midlands",      nearestCity: "Nottingham" },
  { slug: "worksop",              name: "Worksop",            region: "East Midlands",      nearestCity: "Sheffield" },
  { slug: "newark",               name: "Newark",             region: "East Midlands",      nearestCity: "Nottingham" },
  { slug: "grantham",             name: "Grantham",           region: "East Midlands",      nearestCity: "Lincoln" },
  { slug: "buxton",               name: "Buxton",             region: "East Midlands",      nearestCity: "Derby" },
  { slug: "matlock",              name: "Matlock",            region: "East Midlands",      nearestCity: "Derby" },
  { slug: "wellingborough",       name: "Wellingborough",     region: "East Midlands",      nearestCity: "Northampton" },
  { slug: "hinckley",             name: "Hinckley",           region: "East Midlands",      nearestCity: "Leicester" },
  { slug: "nuneaton",             name: "Nuneaton",           region: "East Midlands",      nearestCity: "Coventry" },
  { slug: "melton-mowbray",       name: "Melton Mowbray",     region: "East Midlands",      nearestCity: "Leicester" },
  { slug: "skegness",             name: "Skegness",           region: "East Midlands",      nearestCity: "Lincoln" },
  { slug: "spalding",             name: "Spalding",           region: "East Midlands",      nearestCity: "Peterborough" },
  { slug: "boston",               name: "Boston",             region: "East Midlands",      nearestCity: "Lincoln" },

  // ── WEST MIDLANDS ───────────────────────────────────────────────────────
  { slug: "birmingham",           name: "Birmingham",         region: "West Midlands",      nearestCity: "Birmingham" },
  { slug: "coventry",             name: "Coventry",           region: "West Midlands",      nearestCity: "Coventry" },
  { slug: "wolverhampton",        name: "Wolverhampton",      region: "West Midlands",      nearestCity: "Wolverhampton" },
  { slug: "walsall",              name: "Walsall",            region: "West Midlands",      nearestCity: "Birmingham" },
  { slug: "west-bromwich",        name: "West Bromwich",      region: "West Midlands",      nearestCity: "Birmingham" },
  { slug: "dudley",               name: "Dudley",             region: "West Midlands",      nearestCity: "Birmingham" },
  { slug: "stourbridge",          name: "Stourbridge",        region: "West Midlands",      nearestCity: "Birmingham" },
  { slug: "solihull",             name: "Solihull",           region: "West Midlands",      nearestCity: "Birmingham" },
  { slug: "sutton-coldfield",     name: "Sutton Coldfield",   region: "West Midlands",      nearestCity: "Birmingham" },
  { slug: "tamworth",             name: "Tamworth",           region: "West Midlands",      nearestCity: "Birmingham" },
  { slug: "lichfield",            name: "Lichfield",          region: "West Midlands",      nearestCity: "Birmingham" },
  { slug: "cannock",              name: "Cannock",            region: "West Midlands",      nearestCity: "Wolverhampton" },
  { slug: "redditch",             name: "Redditch",           region: "West Midlands",      nearestCity: "Birmingham" },
  { slug: "kidderminster",        name: "Kidderminster",      region: "West Midlands",      nearestCity: "Birmingham" },
  { slug: "stafford",             name: "Stafford",           region: "Staffordshire",      nearestCity: "Wolverhampton" },
  { slug: "stoke-on-trent",       name: "Stoke-on-Trent",     region: "Staffordshire",      nearestCity: "Stoke-on-Trent" },
  { slug: "newcastle-under-lyme", name: "Newcastle-under-Lyme", region: "Staffordshire",    nearestCity: "Stoke-on-Trent" },
  { slug: "burton-on-trent",      name: "Burton-on-Trent",    region: "Staffordshire",      nearestCity: "Derby" },
  { slug: "shrewsbury",           name: "Shrewsbury",         region: "Shropshire",         nearestCity: "Shrewsbury" },
  { slug: "telford",              name: "Telford",            region: "Shropshire",         nearestCity: "Shrewsbury" },
  { slug: "worcester",            name: "Worcester",          region: "Worcestershire",     nearestCity: "Worcester" },
  { slug: "hereford",             name: "Hereford",           region: "Herefordshire",      nearestCity: "Hereford" },

  // ── EAST OF ENGLAND ─────────────────────────────────────────────────────
  { slug: "cambridge",            name: "Cambridge",          region: "Cambridgeshire",     nearestCity: "Cambridge" },
  { slug: "peterborough",         name: "Peterborough",       region: "Cambridgeshire",     nearestCity: "Peterborough" },
  { slug: "ely",                  name: "Ely",                region: "Cambridgeshire",     nearestCity: "Cambridge" },
  { slug: "huntingdon",           name: "Huntingdon",         region: "Cambridgeshire",     nearestCity: "Peterborough" },
  { slug: "st-neots",             name: "St Neots",           region: "Cambridgeshire",     nearestCity: "Cambridge" },
  { slug: "norwich",              name: "Norwich",            region: "Norfolk",            nearestCity: "Norwich" },
  { slug: "great-yarmouth",       name: "Great Yarmouth",     region: "Norfolk",            nearestCity: "Norwich" },
  { slug: "kings-lynn",           name: "Kings Lynn",         region: "Norfolk",            nearestCity: "Norwich" },
  { slug: "ipswich",              name: "Ipswich",            region: "Suffolk",            nearestCity: "Ipswich" },
  { slug: "lowestoft",            name: "Lowestoft",          region: "Suffolk",            nearestCity: "Norwich" },
  { slug: "bury-st-edmunds",      name: "Bury St Edmunds",    region: "Suffolk",            nearestCity: "Ipswich" },
  { slug: "colchester",           name: "Colchester",         region: "Essex",              nearestCity: "Colchester" },
  { slug: "chelmsford",           name: "Chelmsford",         region: "Essex",              nearestCity: "Chelmsford" },
  { slug: "southend-on-sea",      name: "Southend-on-Sea",    region: "Essex",              nearestCity: "Chelmsford" },
  { slug: "basildon",             name: "Basildon",           region: "Essex",              nearestCity: "Chelmsford" },
  { slug: "harlow",               name: "Harlow",             region: "Essex",              nearestCity: "Chelmsford" },
  { slug: "brentwood",            name: "Brentwood",          region: "Essex",              nearestCity: "Chelmsford" },
  { slug: "clacton-on-sea",       name: "Clacton-on-Sea",     region: "Essex",              nearestCity: "Colchester" },
  { slug: "watford",              name: "Watford",            region: "Hertfordshire",      nearestCity: "Watford" },
  { slug: "hemel-hempstead",      name: "Hemel Hempstead",    region: "Hertfordshire",      nearestCity: "Watford" },
  { slug: "st-albans",            name: "St Albans",          region: "Hertfordshire",      nearestCity: "Watford" },
  { slug: "stevenage",            name: "Stevenage",          region: "Hertfordshire",      nearestCity: "Watford" },
  { slug: "hatfield",             name: "Hatfield",           region: "Hertfordshire",      nearestCity: "Watford" },
  { slug: "welwyn-garden-city",   name: "Welwyn Garden City", region: "Hertfordshire",      nearestCity: "Watford" },
  { slug: "hitchin",              name: "Hitchin",            region: "Hertfordshire",      nearestCity: "Watford" },
  { slug: "luton",                name: "Luton",              region: "Bedfordshire",       nearestCity: "Luton" },
  { slug: "bedford",              name: "Bedford",            region: "Bedfordshire",       nearestCity: "Bedford" },
  { slug: "dunstable",            name: "Dunstable",          region: "Bedfordshire",       nearestCity: "Luton" },

  // ── LONDON ──────────────────────────────────────────────────────────────
  { slug: "london",               name: "London",             region: "London",             nearestCity: "London" },
  { slug: "central-london",       name: "Central London",     region: "London",             nearestCity: "London" },
  { slug: "east-london",          name: "East London",        region: "London",             nearestCity: "London" },
  { slug: "north-london",         name: "North London",       region: "London",             nearestCity: "London" },
  { slug: "south-london",         name: "South London",       region: "London",             nearestCity: "London" },
  { slug: "west-london",          name: "West London",        region: "London",             nearestCity: "London" },
  { slug: "croydon",              name: "Croydon",            region: "London",             nearestCity: "London" },
  { slug: "bromley",              name: "Bromley",            region: "London",             nearestCity: "London" },
  { slug: "wimbledon",            name: "Wimbledon",          region: "London",             nearestCity: "London" },
  { slug: "richmond",             name: "Richmond",           region: "London",             nearestCity: "London" },
  { slug: "twickenham",           name: "Twickenham",         region: "London",             nearestCity: "London" },
  { slug: "kingston-upon-thames", name: "Kingston upon Thames", region: "London",           nearestCity: "London" },
  { slug: "hounslow",             name: "Hounslow",           region: "London",             nearestCity: "London" },
  { slug: "ealing",               name: "Ealing",             region: "London",             nearestCity: "London" },
  { slug: "chiswick",             name: "Chiswick",           region: "London",             nearestCity: "London" },
  { slug: "hammersmith",          name: "Hammersmith",        region: "London",             nearestCity: "London" },
  { slug: "fulham",               name: "Fulham",             region: "London",             nearestCity: "London" },
  { slug: "chelsea",              name: "Chelsea",            region: "London",             nearestCity: "London" },
  { slug: "kensington",           name: "Kensington",         region: "London",             nearestCity: "London" },
  { slug: "westminster",          name: "Westminster",        region: "London",             nearestCity: "London" },
  { slug: "camden",               name: "Camden",             region: "London",             nearestCity: "London" },
  { slug: "islington",            name: "Islington",          region: "London",             nearestCity: "London" },
  { slug: "hackney",              name: "Hackney",            region: "London",             nearestCity: "London" },
  { slug: "shoreditch",           name: "Shoreditch",         region: "London",             nearestCity: "London" },
  { slug: "canary-wharf",         name: "Canary Wharf",       region: "London",             nearestCity: "London" },
  { slug: "stratford",            name: "Stratford",          region: "London",             nearestCity: "London" },
  { slug: "ilford",               name: "Ilford",             region: "London",             nearestCity: "London" },
  { slug: "romford",              name: "Romford",            region: "London",             nearestCity: "London" },
  { slug: "barking",              name: "Barking",            region: "London",             nearestCity: "London" },
  { slug: "greenwich",            name: "Greenwich",          region: "London",             nearestCity: "London" },
  { slug: "lewisham",             name: "Lewisham",           region: "London",             nearestCity: "London" },
  { slug: "southwark",            name: "Southwark",          region: "London",             nearestCity: "London" },
  { slug: "lambeth",              name: "Lambeth",            region: "London",             nearestCity: "London" },
  { slug: "wandsworth",           name: "Wandsworth",         region: "London",             nearestCity: "London" },
  { slug: "tooting",              name: "Tooting",            region: "London",             nearestCity: "London" },
  { slug: "brixton",              name: "Brixton",            region: "London",             nearestCity: "London" },
  { slug: "clapham",              name: "Clapham",            region: "London",             nearestCity: "London" },
  { slug: "harrow",               name: "Harrow",             region: "London",             nearestCity: "London" },
  { slug: "wembley",              name: "Wembley",            region: "London",             nearestCity: "London" },
  { slug: "uxbridge",             name: "Uxbridge",           region: "London",             nearestCity: "London" },
  { slug: "enfield",              name: "Enfield",            region: "London",             nearestCity: "London" },
  { slug: "barnet",               name: "Barnet",             region: "London",             nearestCity: "London" },
  { slug: "tottenham",            name: "Tottenham",          region: "London",             nearestCity: "London" },
  { slug: "wood-green",           name: "Wood Green",         region: "London",             nearestCity: "London" },
  { slug: "finchley",             name: "Finchley",           region: "London",             nearestCity: "London" },
  { slug: "stoke-newington",      name: "Stoke Newington",    region: "London",             nearestCity: "London" },
  { slug: "dalston",              name: "Dalston",            region: "London",             nearestCity: "London" },
  { slug: "peckham",              name: "Peckham",            region: "London",             nearestCity: "London" },
  { slug: "deptford",             name: "Deptford",           region: "London",             nearestCity: "London" },
  { slug: "woolwich",             name: "Woolwich",           region: "London",             nearestCity: "London" },
  { slug: "eltham",               name: "Eltham",             region: "London",             nearestCity: "London" },
  { slug: "sutton",               name: "Sutton",             region: "London",             nearestCity: "London" },
  { slug: "merton",               name: "Merton",             region: "London",             nearestCity: "London" },

  // ── SOUTH EAST ENGLAND ──────────────────────────────────────────────────
  { slug: "brighton",             name: "Brighton",           region: "East Sussex",        nearestCity: "Brighton" },
  { slug: "hove",                 name: "Hove",               region: "East Sussex",        nearestCity: "Brighton" },
  { slug: "eastbourne",           name: "Eastbourne",         region: "East Sussex",        nearestCity: "Brighton" },
  { slug: "hastings",             name: "Hastings",           region: "East Sussex",        nearestCity: "Brighton" },
  { slug: "lewes",                name: "Lewes",              region: "East Sussex",        nearestCity: "Brighton" },
  { slug: "worthing",             name: "Worthing",           region: "West Sussex",        nearestCity: "Brighton" },
  { slug: "crawley",              name: "Crawley",            region: "West Sussex",        nearestCity: "Brighton" },
  { slug: "chichester",           name: "Chichester",         region: "West Sussex",        nearestCity: "Brighton" },
  { slug: "bognor-regis",         name: "Bognor Regis",       region: "West Sussex",        nearestCity: "Brighton" },
  { slug: "horsham",              name: "Horsham",            region: "West Sussex",        nearestCity: "Brighton" },
  { slug: "guildford",            name: "Guildford",          region: "Surrey",             nearestCity: "Guildford" },
  { slug: "woking",               name: "Woking",             region: "Surrey",             nearestCity: "Guildford" },
  { slug: "farnham",              name: "Farnham",            region: "Surrey",             nearestCity: "Guildford" },
  { slug: "epsom",                name: "Epsom",              region: "Surrey",             nearestCity: "Guildford" },
  { slug: "redhill",              name: "Redhill",            region: "Surrey",             nearestCity: "Guildford" },
  { slug: "reigate",              name: "Reigate",            region: "Surrey",             nearestCity: "Guildford" },
  { slug: "camberley",            name: "Camberley",          region: "Surrey",             nearestCity: "Guildford" },
  { slug: "aldershot",            name: "Aldershot",          region: "Hampshire",          nearestCity: "Southampton" },
  { slug: "farnborough",          name: "Farnborough",        region: "Hampshire",          nearestCity: "Southampton" },
  { slug: "basingstoke",          name: "Basingstoke",        region: "Hampshire",          nearestCity: "Southampton" },
  { slug: "winchester",           name: "Winchester",         region: "Hampshire",          nearestCity: "Southampton" },
  { slug: "southampton",          name: "Southampton",        region: "Hampshire",          nearestCity: "Southampton" },
  { slug: "portsmouth",           name: "Portsmouth",         region: "Hampshire",          nearestCity: "Portsmouth" },
  { slug: "fareham",              name: "Fareham",            region: "Hampshire",          nearestCity: "Portsmouth" },
  { slug: "gosport",              name: "Gosport",            region: "Hampshire",          nearestCity: "Portsmouth" },
  { slug: "eastleigh",            name: "Eastleigh",          region: "Hampshire",          nearestCity: "Southampton" },
  { slug: "andover",              name: "Andover",            region: "Hampshire",          nearestCity: "Southampton" },
  { slug: "tunbridge-wells",      name: "Tunbridge Wells",    region: "Kent",               nearestCity: "Maidstone" },
  { slug: "maidstone",            name: "Maidstone",          region: "Kent",               nearestCity: "Maidstone" },
  { slug: "ashford",              name: "Ashford",            region: "Kent",               nearestCity: "Maidstone" },
  { slug: "folkestone",           name: "Folkestone",         region: "Kent",               nearestCity: "Maidstone" },
  { slug: "dover",                name: "Dover",              region: "Kent",               nearestCity: "Maidstone" },
  { slug: "canterbury",           name: "Canterbury",         region: "Kent",               nearestCity: "Canterbury" },
  { slug: "chatham",              name: "Chatham",            region: "Kent",               nearestCity: "Maidstone" },
  { slug: "rochester",            name: "Rochester",          region: "Kent",               nearestCity: "Maidstone" },
  { slug: "dartford",             name: "Dartford",           region: "Kent",               nearestCity: "Maidstone" },
  { slug: "gravesend",            name: "Gravesend",          region: "Kent",               nearestCity: "Maidstone" },
  { slug: "sittingbourne",        name: "Sittingbourne",      region: "Kent",               nearestCity: "Maidstone" },
  { slug: "margate",              name: "Margate",            region: "Kent",               nearestCity: "Canterbury" },
  { slug: "ramsgate",             name: "Ramsgate",           region: "Kent",               nearestCity: "Canterbury" },
  { slug: "reading",              name: "Reading",            region: "Berkshire",          nearestCity: "Reading" },
  { slug: "slough",               name: "Slough",             region: "Berkshire",          nearestCity: "Reading" },
  { slug: "windsor",              name: "Windsor",            region: "Berkshire",          nearestCity: "Reading" },
  { slug: "maidenhead",           name: "Maidenhead",         region: "Berkshire",          nearestCity: "Reading" },
  { slug: "bracknell",            name: "Bracknell",          region: "Berkshire",          nearestCity: "Reading" },
  { slug: "oxford",               name: "Oxford",             region: "Oxfordshire",        nearestCity: "Oxford" },
  { slug: "banbury",              name: "Banbury",            region: "Oxfordshire",        nearestCity: "Oxford" },
  { slug: "witney",               name: "Witney",             region: "Oxfordshire",        nearestCity: "Oxford" },
  { slug: "abingdon",             name: "Abingdon",           region: "Oxfordshire",        nearestCity: "Oxford" },
  { slug: "milton-keynes",        name: "Milton Keynes",      region: "Buckinghamshire",    nearestCity: "Milton Keynes" },
  { slug: "aylesbury",            name: "Aylesbury",          region: "Buckinghamshire",    nearestCity: "Milton Keynes" },
  { slug: "high-wycombe",         name: "High Wycombe",       region: "Buckinghamshire",    nearestCity: "Milton Keynes" },
  { slug: "amersham",             name: "Amersham",           region: "Buckinghamshire",    nearestCity: "Milton Keynes" },
  { slug: "marlow",               name: "Marlow",             region: "Buckinghamshire",    nearestCity: "Reading" },

  // ── SOUTH WEST ENGLAND ──────────────────────────────────────────────────
  { slug: "bristol",              name: "Bristol",            region: "Bristol",            nearestCity: "Bristol" },
  { slug: "bath",                 name: "Bath",               region: "Somerset",           nearestCity: "Bristol" },
  { slug: "swindon",              name: "Swindon",            region: "Wiltshire",          nearestCity: "Bristol" },
  { slug: "gloucester",           name: "Gloucester",         region: "Gloucestershire",    nearestCity: "Bristol" },
  { slug: "cheltenham",           name: "Cheltenham",         region: "Gloucestershire",    nearestCity: "Bristol" },
  { slug: "stroud",               name: "Stroud",             region: "Gloucestershire",    nearestCity: "Bristol" },
  { slug: "cirencester",          name: "Cirencester",        region: "Gloucestershire",    nearestCity: "Bristol" },
  { slug: "exeter",               name: "Exeter",             region: "Devon",              nearestCity: "Exeter" },
  { slug: "plymouth",             name: "Plymouth",           region: "Devon",              nearestCity: "Plymouth" },
  { slug: "torquay",              name: "Torquay",            region: "Devon",              nearestCity: "Exeter" },
  { slug: "paignton",             name: "Paignton",           region: "Devon",              nearestCity: "Exeter" },
  { slug: "barnstaple",           name: "Barnstaple",         region: "Devon",              nearestCity: "Exeter" },
  { slug: "newton-abbot",         name: "Newton Abbot",       region: "Devon",              nearestCity: "Exeter" },
  { slug: "taunton",              name: "Taunton",            region: "Somerset",           nearestCity: "Bristol" },
  { slug: "weston-super-mare",    name: "Weston-super-Mare",  region: "Somerset",           nearestCity: "Bristol" },
  { slug: "yeovil",               name: "Yeovil",             region: "Somerset",           nearestCity: "Bristol" },
  { slug: "bridgwater",           name: "Bridgwater",         region: "Somerset",           nearestCity: "Bristol" },
  { slug: "bournemouth",          name: "Bournemouth",        region: "Dorset",             nearestCity: "Bournemouth" },
  { slug: "poole",                name: "Poole",              region: "Dorset",             nearestCity: "Bournemouth" },
  { slug: "weymouth",             name: "Weymouth",           region: "Dorset",             nearestCity: "Bournemouth" },
  { slug: "dorchester",           name: "Dorchester",         region: "Dorset",             nearestCity: "Bournemouth" },
  { slug: "christchurch",         name: "Christchurch",       region: "Dorset",             nearestCity: "Bournemouth" },
  { slug: "truro",                name: "Truro",              region: "Cornwall",           nearestCity: "Truro" },
  { slug: "falmouth",             name: "Falmouth",           region: "Cornwall",           nearestCity: "Truro" },
  { slug: "penzance",             name: "Penzance",           region: "Cornwall",           nearestCity: "Truro" },
  { slug: "newquay",              name: "Newquay",            region: "Cornwall",           nearestCity: "Truro" },
  { slug: "st-austell",           name: "St Austell",         region: "Cornwall",           nearestCity: "Truro" },
  { slug: "bodmin",               name: "Bodmin",             region: "Cornwall",           nearestCity: "Truro" },
  { slug: "salisbury",            name: "Salisbury",          region: "Wiltshire",          nearestCity: "Salisbury" },
  { slug: "chippenham",           name: "Chippenham",         region: "Wiltshire",          nearestCity: "Bristol" },
  { slug: "trowbridge",           name: "Trowbridge",         region: "Wiltshire",          nearestCity: "Bristol" },

  // ── SCOTLAND ────────────────────────────────────────────────────────────
  { slug: "glasgow",              name: "Glasgow",            region: "Scotland",           nearestCity: "Glasgow" },
  { slug: "edinburgh",            name: "Edinburgh",          region: "Scotland",           nearestCity: "Edinburgh" },
  { slug: "aberdeen",             name: "Aberdeen",           region: "Scotland",           nearestCity: "Aberdeen" },
  { slug: "dundee",               name: "Dundee",             region: "Scotland",           nearestCity: "Dundee" },
  { slug: "inverness",            name: "Inverness",          region: "Scotland",           nearestCity: "Inverness" },
  { slug: "stirling",             name: "Stirling",           region: "Scotland",           nearestCity: "Stirling" },
  { slug: "perth",                name: "Perth",              region: "Scotland",           nearestCity: "Perth" },
  { slug: "livingston",           name: "Livingston",         region: "Scotland",           nearestCity: "Edinburgh" },
  { slug: "falkirk",              name: "Falkirk",            region: "Scotland",           nearestCity: "Stirling" },
  { slug: "motherwell",           name: "Motherwell",         region: "Scotland",           nearestCity: "Glasgow" },
  { slug: "hamilton",             name: "Hamilton",           region: "Scotland",           nearestCity: "Glasgow" },
  { slug: "east-kilbride",        name: "East Kilbride",      region: "Scotland",           nearestCity: "Glasgow" },
  { slug: "paisley",              name: "Paisley",            region: "Scotland",           nearestCity: "Glasgow" },
  { slug: "greenock",             name: "Greenock",           region: "Scotland",           nearestCity: "Glasgow" },
  { slug: "ayr",                  name: "Ayr",                region: "Scotland",           nearestCity: "Glasgow" },
  { slug: "kilmarnock",           name: "Kilmarnock",         region: "Scotland",           nearestCity: "Glasgow" },
  { slug: "dunfermline",          name: "Dunfermline",        region: "Scotland",           nearestCity: "Edinburgh" },
  { slug: "kirkcaldy",            name: "Kirkcaldy",          region: "Scotland",           nearestCity: "Edinburgh" },
  { slug: "dumfries",             name: "Dumfries",           region: "Scotland",           nearestCity: "Dumfries" },
  { slug: "st-andrews",           name: "St Andrews",         region: "Scotland",           nearestCity: "Dundee" },
  { slug: "cumbernauld",          name: "Cumbernauld",        region: "Scotland",           nearestCity: "Glasgow" },
  { slug: "coatbridge",           name: "Coatbridge",         region: "Scotland",           nearestCity: "Glasgow" },
  { slug: "airdrie",              name: "Airdrie",            region: "Scotland",           nearestCity: "Glasgow" },

  // ── WALES ───────────────────────────────────────────────────────────────
  { slug: "cardiff",              name: "Cardiff",            region: "Wales",              nearestCity: "Cardiff" },
  { slug: "swansea",              name: "Swansea",            region: "Wales",              nearestCity: "Swansea" },
  { slug: "newport",              name: "Newport",            region: "Wales",              nearestCity: "Cardiff" },
  { slug: "wrexham",              name: "Wrexham",            region: "Wales",              nearestCity: "Wrexham" },
  { slug: "barry",                name: "Barry",              region: "Wales",              nearestCity: "Cardiff" },
  { slug: "bridgend",             name: "Bridgend",           region: "Wales",              nearestCity: "Cardiff" },
  { slug: "merthyr-tydfil",       name: "Merthyr Tydfil",     region: "Wales",              nearestCity: "Cardiff" },
  { slug: "caerphilly",           name: "Caerphilly",         region: "Wales",              nearestCity: "Cardiff" },
  { slug: "neath",                name: "Neath",              region: "Wales",              nearestCity: "Swansea" },
  { slug: "port-talbot",          name: "Port Talbot",        region: "Wales",              nearestCity: "Swansea" },
  { slug: "llanelli",             name: "Llanelli",           region: "Wales",              nearestCity: "Swansea" },
  { slug: "pontypridd",           name: "Pontypridd",         region: "Wales",              nearestCity: "Cardiff" },
  { slug: "rhondda",              name: "Rhondda",            region: "Wales",              nearestCity: "Cardiff" },
  { slug: "carmarthen",           name: "Carmarthen",         region: "Wales",              nearestCity: "Swansea" },
  { slug: "aberystwyth",          name: "Aberystwyth",        region: "Wales",              nearestCity: "Aberystwyth" },
  { slug: "bangor-wales",         name: "Bangor",             region: "Wales",              nearestCity: "Bangor" },
  { slug: "rhyl",                 name: "Rhyl",               region: "Wales",              nearestCity: "Wrexham" },
  { slug: "colwyn-bay",           name: "Colwyn Bay",         region: "Wales",              nearestCity: "Wrexham" },
  { slug: "flint",                name: "Flint",              region: "Wales",              nearestCity: "Wrexham" },

  // ── NORTHERN IRELAND ────────────────────────────────────────────────────
  { slug: "belfast",              name: "Belfast",            region: "Northern Ireland",   nearestCity: "Belfast" },
  { slug: "derry",                name: "Derry",              region: "Northern Ireland",   nearestCity: "Derry" },
  { slug: "lisburn",              name: "Lisburn",            region: "Northern Ireland",   nearestCity: "Belfast" },
  { slug: "newry",                name: "Newry",              region: "Northern Ireland",   nearestCity: "Belfast" },
  { slug: "armagh",               name: "Armagh",             region: "Northern Ireland",   nearestCity: "Belfast" },
  { slug: "omagh",                name: "Omagh",              region: "Northern Ireland",   nearestCity: "Derry" },
  { slug: "ballymena",            name: "Ballymena",          region: "Northern Ireland",   nearestCity: "Belfast" },
  { slug: "coleraine",            name: "Coleraine",          region: "Northern Ireland",   nearestCity: "Derry" },
  { slug: "antrim",               name: "Antrim",             region: "Northern Ireland",   nearestCity: "Belfast" },
  { slug: "newtownabbey",         name: "Newtownabbey",       region: "Northern Ireland",   nearestCity: "Belfast" },
  { slug: "bangor-ni",            name: "Bangor",             region: "Northern Ireland",   nearestCity: "Belfast" },
  { slug: "carrickfergus",        name: "Carrickfergus",      region: "Northern Ireland",   nearestCity: "Belfast" },
  { slug: "enniskillen",          name: "Enniskillen",        region: "Northern Ireland",   nearestCity: "Enniskillen" },
]

export function getLocationBySlug(slug: string): UKLocation | undefined {
  return ukLocations.find((l) => l.slug === slug)
}
