export interface YorkshireLocation {
  slug: string
  name: string
  region: string
  nearestCity: string
}

export const yorkshireLocations: YorkshireLocation[] = [
  // West Yorkshire
  { slug: "leeds",           name: "Leeds",           region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "bradford",        name: "Bradford",        region: "West Yorkshire",  nearestCity: "Bradford" },
  { slug: "wakefield",       name: "Wakefield",       region: "West Yorkshire",  nearestCity: "Wakefield" },
  { slug: "huddersfield",    name: "Huddersfield",    region: "West Yorkshire",  nearestCity: "Huddersfield" },
  { slug: "halifax",         name: "Halifax",         region: "West Yorkshire",  nearestCity: "Halifax" },
  { slug: "pontefract",      name: "Pontefract",      region: "West Yorkshire",  nearestCity: "Wakefield" },
  { slug: "normanton",       name: "Normanton",       region: "West Yorkshire",  nearestCity: "Wakefield" },
  { slug: "castleford",      name: "Castleford",      region: "West Yorkshire",  nearestCity: "Wakefield" },
  { slug: "dewsbury",        name: "Dewsbury",        region: "West Yorkshire",  nearestCity: "Huddersfield" },
  { slug: "batley",          name: "Batley",          region: "West Yorkshire",  nearestCity: "Huddersfield" },
  { slug: "morley",          name: "Morley",          region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "ossett",          name: "Ossett",          region: "West Yorkshire",  nearestCity: "Wakefield" },
  { slug: "horsforth",       name: "Horsforth",       region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "keighley",        name: "Keighley",        region: "West Yorkshire",  nearestCity: "Bradford" },
  { slug: "bingley",         name: "Bingley",         region: "West Yorkshire",  nearestCity: "Bradford" },
  { slug: "shipley",         name: "Shipley",         region: "West Yorkshire",  nearestCity: "Bradford" },
  { slug: "otley",           name: "Otley",           region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "ilkley",          name: "Ilkley",          region: "West Yorkshire",  nearestCity: "Bradford" },
  { slug: "wetherby",        name: "Wetherby",        region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "garforth",        name: "Garforth",        region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "pudsey",          name: "Pudsey",          region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "rothwell",        name: "Rothwell",        region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "brighouse",       name: "Brighouse",       region: "West Yorkshire",  nearestCity: "Halifax" },
  { slug: "elland",          name: "Elland",          region: "West Yorkshire",  nearestCity: "Halifax" },
  { slug: "sowerby-bridge",  name: "Sowerby Bridge",  region: "West Yorkshire",  nearestCity: "Halifax" },
  { slug: "todmorden",       name: "Todmorden",       region: "West Yorkshire",  nearestCity: "Halifax" },
  { slug: "hebden-bridge",   name: "Hebden Bridge",   region: "West Yorkshire",  nearestCity: "Halifax" },
  { slug: "featherstone",    name: "Featherstone",    region: "West Yorkshire",  nearestCity: "Wakefield" },
  { slug: "knottingley",     name: "Knottingley",     region: "West Yorkshire",  nearestCity: "Wakefield" },
  { slug: "hemsworth",       name: "Hemsworth",       region: "West Yorkshire",  nearestCity: "Wakefield" },
  { slug: "cleckheaton",     name: "Cleckheaton",     region: "West Yorkshire",  nearestCity: "Bradford" },
  { slug: "heckmondwike",    name: "Heckmondwike",    region: "West Yorkshire",  nearestCity: "Huddersfield" },
  { slug: "mirfield",        name: "Mirfield",        region: "West Yorkshire",  nearestCity: "Huddersfield" },
  { slug: "liversedge",      name: "Liversedge",      region: "West Yorkshire",  nearestCity: "Bradford" },
  { slug: "spenborough",     name: "Spenborough",     region: "West Yorkshire",  nearestCity: "Bradford" },
  { slug: "yeadon",          name: "Yeadon",          region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "guiseley",        name: "Guiseley",        region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "rawdon",          name: "Rawdon",          region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "farsley",         name: "Farsley",         region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "stanningley",     name: "Stanningley",     region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "armley",          name: "Armley",          region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "beeston",         name: "Beeston",         region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "crossgates",      name: "Cross Gates",     region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "seacroft",        name: "Seacroft",        region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "harehills",       name: "Harehills",       region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "chapeltown",      name: "Chapeltown",      region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "headingley",      name: "Headingley",      region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "meanwood",        name: "Meanwood",        region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "moortown",        name: "Moortown",        region: "West Yorkshire",  nearestCity: "Leeds" },
  { slug: "roundhay",        name: "Roundhay",        region: "West Yorkshire",  nearestCity: "Leeds" },

  // South Yorkshire
  { slug: "sheffield",       name: "Sheffield",       region: "South Yorkshire", nearestCity: "Sheffield" },
  { slug: "rotherham",       name: "Rotherham",       region: "South Yorkshire", nearestCity: "Sheffield" },
  { slug: "barnsley",        name: "Barnsley",        region: "South Yorkshire", nearestCity: "Barnsley" },
  { slug: "doncaster",       name: "Doncaster",       region: "South Yorkshire", nearestCity: "Doncaster" },
  { slug: "mexborough",      name: "Mexborough",      region: "South Yorkshire", nearestCity: "Rotherham" },
  { slug: "rawmarsh",        name: "Rawmarsh",        region: "South Yorkshire", nearestCity: "Rotherham" },
  { slug: "swinton",         name: "Swinton",         region: "South Yorkshire", nearestCity: "Rotherham" },
  { slug: "maltby",          name: "Maltby",          region: "South Yorkshire", nearestCity: "Rotherham" },
  { slug: "worsbrough",      name: "Worsbrough",      region: "South Yorkshire", nearestCity: "Barnsley" },
  { slug: "penistone",       name: "Penistone",       region: "South Yorkshire", nearestCity: "Barnsley" },
  { slug: "stocksbridge",    name: "Stocksbridge",    region: "South Yorkshire", nearestCity: "Sheffield" },
  { slug: "chapeltown-sheffield", name: "Chapeltown", region: "South Yorkshire", nearestCity: "Sheffield" },
  { slug: "ecclesfield",     name: "Ecclesfield",     region: "South Yorkshire", nearestCity: "Sheffield" },
  { slug: "aughton",         name: "Aughton",         region: "South Yorkshire", nearestCity: "Rotherham" },
  { slug: "wath-upon-dearne", name: "Wath-upon-Dearne", region: "South Yorkshire", nearestCity: "Rotherham" },
  { slug: "thurnscoe",       name: "Thurnscoe",       region: "South Yorkshire", nearestCity: "Barnsley" },
  { slug: "goldthorpe",      name: "Goldthorpe",      region: "South Yorkshire", nearestCity: "Barnsley" },
  { slug: "conisbrough",     name: "Conisbrough",     region: "South Yorkshire", nearestCity: "Doncaster" },
  { slug: "adwick-le-street", name: "Adwick le Street", region: "South Yorkshire", nearestCity: "Doncaster" },
  { slug: "armthorpe",       name: "Armthorpe",       region: "South Yorkshire", nearestCity: "Doncaster" },
  { slug: "bentley",         name: "Bentley",         region: "South Yorkshire", nearestCity: "Doncaster" },

  // North Yorkshire
  { slug: "york",            name: "York",            region: "North Yorkshire", nearestCity: "York" },
  { slug: "harrogate",       name: "Harrogate",       region: "North Yorkshire", nearestCity: "Harrogate" },
  { slug: "scarborough",     name: "Scarborough",     region: "North Yorkshire", nearestCity: "Scarborough" },
  { slug: "northallerton",   name: "Northallerton",   region: "North Yorkshire", nearestCity: "Northallerton" },
  { slug: "ripon",           name: "Ripon",           region: "North Yorkshire", nearestCity: "Harrogate" },
  { slug: "skipton",         name: "Skipton",         region: "North Yorkshire", nearestCity: "Skipton" },
  { slug: "whitby",          name: "Whitby",          region: "North Yorkshire", nearestCity: "Scarborough" },
  { slug: "pickering",       name: "Pickering",       region: "North Yorkshire", nearestCity: "Scarborough" },
  { slug: "thirsk",          name: "Thirsk",          region: "North Yorkshire", nearestCity: "Northallerton" },
  { slug: "knaresborough",   name: "Knaresborough",   region: "North Yorkshire", nearestCity: "Harrogate" },
  { slug: "selby",           name: "Selby",           region: "North Yorkshire", nearestCity: "York" },
  { slug: "tadcaster",       name: "Tadcaster",       region: "North Yorkshire", nearestCity: "York" },
  { slug: "boroughbridge",   name: "Boroughbridge",   region: "North Yorkshire", nearestCity: "Harrogate" },
  { slug: "malton",          name: "Malton",          region: "North Yorkshire", nearestCity: "York" },
  { slug: "filey",           name: "Filey",           region: "North Yorkshire", nearestCity: "Scarborough" },
  { slug: "helmsley",        name: "Helmsley",        region: "North Yorkshire", nearestCity: "York" },
  { slug: "bedale",          name: "Bedale",          region: "North Yorkshire", nearestCity: "Northallerton" },
  { slug: "leyburn",         name: "Leyburn",         region: "North Yorkshire", nearestCity: "Northallerton" },
  { slug: "masham",          name: "Masham",          region: "North Yorkshire", nearestCity: "Harrogate" },
  { slug: "pateley-bridge",  name: "Pateley Bridge",  region: "North Yorkshire", nearestCity: "Harrogate" },
  { slug: "richmond",        name: "Richmond",        region: "North Yorkshire", nearestCity: "Northallerton" },
  { slug: "settle",          name: "Settle",          region: "North Yorkshire", nearestCity: "Skipton" },
  { slug: "grassington",     name: "Grassington",     region: "North Yorkshire", nearestCity: "Skipton" },

  // East Yorkshire
  { slug: "hull",            name: "Hull",            region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "beverley",        name: "Beverley",        region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "bridlington",     name: "Bridlington",     region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "driffield",       name: "Driffield",       region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "hornsea",         name: "Hornsea",         region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "withernsea",      name: "Withernsea",      region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "goole",           name: "Goole",           region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "pocklington",     name: "Pocklington",     region: "East Yorkshire",  nearestCity: "York" },
  { slug: "market-weighton", name: "Market Weighton", region: "East Yorkshire",  nearestCity: "York" },
  { slug: "hessle",          name: "Hessle",          region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "cottingham",      name: "Cottingham",      region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "anlaby",          name: "Anlaby",          region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "brough",          name: "Brough",          region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "hedon",           name: "Hedon",           region: "East Yorkshire",  nearestCity: "Hull" },
  { slug: "howden",          name: "Howden",          region: "East Yorkshire",  nearestCity: "Goole" },
  { slug: "snaith",          name: "Snaith",          region: "East Yorkshire",  nearestCity: "Goole" },
]

export function getLocationBySlug(slug: string): YorkshireLocation | undefined {
  return yorkshireLocations.find((l) => l.slug === slug)
}
