// Auto-generated by build_transcripts.mjs — DO NOT EDIT.
// Lightweight metadata index. Per-episode paragraphs live in <slug>.json.

export interface EpisodeIndex {
  id: string;
  slug: string;
  ep: number | null;
  title: string;
  date: string;
  category: 'transformation' | 'business' | 'industry';
  wordCount: number;
}

export const episodesIndex: EpisodeIndex[] = [
  {
    "id": "pekkJVhEY8w",
    "slug": "ai-glp-1s-and-the-death-of-the-20-personal-trainer",
    "ep": 34,
    "title": "AI, GLP-1s and the Death of the £20 Personal Trainer — PT Launch Lab LIVE",
    "date": "2026-08-04",
    "category": "industry",
    "wordCount": 15522
  },
  {
    "id": "vUaye0j8p34",
    "slug": "ridge-holland-on-big-e-rugby-league-and-life-after-wwe",
    "ep": 33,
    "title": "Ridge Holland on Big E, Rugby League & Life After WWE",
    "date": "2026-05-04",
    "category": "industry",
    "wordCount": 10518
  },
  {
    "id": "-ZHxWBvBYrw",
    "slug": "why-in-person-personal-training-will-be-ai-proof-sohail-rashid",
    "ep": 32,
    "title": "Why In-Person Personal Training Will Be AI-Proof — Sohail Rashid",
    "date": "2026-04-30",
    "category": "business",
    "wordCount": 14835
  },
  {
    "id": "l5SsHmySSEs",
    "slug": "royal-marines-and-afghanistan-to-personal-trainer-the-truth-about-this-industry",
    "ep": 31,
    "title": "Royal Marines & Afghanistan to Personal Trainer — The Truth About This Industry",
    "date": "2026-04-16",
    "category": "transformation",
    "wordCount": 9381
  },
  {
    "id": "vnsAYYOpshg",
    "slug": "from-council-estate-to-stage-with-dizzee-rascal-now-im-a-personal-trainer",
    "ep": 30,
    "title": "From Council Estate to Stage with Dizzee Rascal — Now I'm a Personal Trainer",
    "date": "2026-04-14",
    "category": "transformation",
    "wordCount": 10547
  },
  {
    "id": "n4h2p1eE_Qw",
    "slug": "what-90-of-blood-tests-reveal-even-when-you-feel-fine",
    "ep": 29,
    "title": "What 90% of Blood Tests Reveal (Even When You Feel Fine)",
    "date": "2026-04-13",
    "category": "industry",
    "wordCount": 10258
  },
  {
    "id": "Z6eogOvRtw0",
    "slug": "from-icu-nurse-to-fitness-business-marias-career-change",
    "ep": 28,
    "title": "From ICU Nurse to Fitness Business: Maria's Career Change",
    "date": "2026-03-15",
    "category": "transformation",
    "wordCount": 9406
  },
  {
    "id": "bpESntFMy0w",
    "slug": "from-addiction-to-full-time-boxing-coach-pembos-story",
    "ep": 27,
    "title": "From Addiction to Full-Time Boxing Coach: Pembo's Story",
    "date": "2026-02-10",
    "category": "transformation",
    "wordCount": 7368
  },
  {
    "id": "tgDP_hoObwM",
    "slug": "building-a-martial-arts-gym-from-scratch-ty-harrison",
    "ep": 26,
    "title": "Building a Martial Arts Gym from Scratch — Ty Harrison",
    "date": "2026-01-28",
    "category": "industry",
    "wordCount": 10039
  },
  {
    "id": "C8t9nC2HxOM",
    "slug": "world-class-dancer-to-yoga-studio-owner-lauras-story",
    "ep": 25,
    "title": "World-Class Dancer to Yoga Studio Owner: Laura's Story",
    "date": "2026-01-21",
    "category": "transformation",
    "wordCount": 9762
  },
  {
    "id": "agtjiOXMKOg",
    "slug": "from-46-stone-to-qualified-personal-trainer-jack-atkinson",
    "ep": 24,
    "title": "From 46 Stone to Qualified Personal Trainer — Jack Atkinson",
    "date": "2026-01-14",
    "category": "transformation",
    "wordCount": 12211
  },
  {
    "id": "70EkHHRizj8",
    "slug": "the-reality-of-running-multiple-fitness-businesses",
    "ep": 23,
    "title": "The Reality of Running Multiple Fitness Businesses",
    "date": "2026-01-01",
    "category": "business",
    "wordCount": 7308
  },
  {
    "id": "4jITjBvGXXU",
    "slug": "british-powerlifting-champion-to-bodybuilding-burnout-sam-hincks",
    "ep": 22,
    "title": "British Powerlifting Champion to Bodybuilding Burnout — Sam Hincks",
    "date": "2025-12-15",
    "category": "industry",
    "wordCount": 12025
  },
  {
    "id": "NrV3eqA3S5Q",
    "slug": "what-most-pts-get-wrong-about-movement-kim-tomlin",
    "ep": 21,
    "title": "What Most PTs Get Wrong About Movement — Kim Tomlin",
    "date": "2025-12-08",
    "category": "industry",
    "wordCount": 9004
  },
  {
    "id": "oQhgsNsLd-8",
    "slug": "how-max-clark-opened-his-own-boxing-gym-at-18",
    "ep": 20,
    "title": "How Max Clark Opened His Own Boxing Gym at 18",
    "date": "2025-11-20",
    "category": "industry",
    "wordCount": 9684
  },
  {
    "id": "gfA-LCPXpBM",
    "slug": "super-league-debut-to-heart-surgery-kiels-story",
    "ep": 19,
    "title": "Super League Debut to Heart Surgery — Kiel's Story",
    "date": "2025-11-10",
    "category": "transformation",
    "wordCount": 12187
  },
  {
    "id": "8477A4T4HBQ",
    "slug": "how-to-scale-your-pt-business-online-with-miles",
    "ep": 16,
    "title": "How to Scale Your PT Business Online — with Miles",
    "date": "2025-10-24",
    "category": "business",
    "wordCount": 10444
  },
  {
    "id": "4r_4ZegftMY",
    "slug": "from-addiction-to-personal-trainer-marcus-mean-and-clean",
    "ep": 15,
    "title": "From Addiction to Personal Trainer — Marcus, Mean and Clean",
    "date": "2025-10-21",
    "category": "transformation",
    "wordCount": 8486
  },
  {
    "id": "d8PxJsyje-o",
    "slug": "3-things-i-wish-i-knew-before-becoming-a-personal-trainer-luke-mccarthy",
    "ep": 14,
    "title": "3 Things I Wish I Knew Before Becoming a Personal Trainer — Luke McCarthy",
    "date": "2025-10-13",
    "category": "business",
    "wordCount": 10276
  },
  {
    "id": "IDkRUIeXU4E",
    "slug": "how-personal-training-made-me-a-better-racing-driver-zak-meakin",
    "ep": 13,
    "title": "How Personal Training Made Me a Better Racing Driver — Zak Meakin",
    "date": "2025-09-24",
    "category": "industry",
    "wordCount": 7862
  },
  {
    "id": "pAm1jvDKRM0",
    "slug": "how-gemma-left-her-corporate-job-to-become-a-personal-trainer",
    "ep": 12,
    "title": "How Gemma Left Her Corporate Job to Become a Personal Trainer",
    "date": "2025-09-12",
    "category": "transformation",
    "wordCount": 7019
  },
  {
    "id": "ZlZxHBwliIk",
    "slug": "how-running-saved-me-from-addiction-matty-bell",
    "ep": 11,
    "title": "How Running Saved Me from Addiction — Matty Bell",
    "date": "2025-09-06",
    "category": "transformation",
    "wordCount": 5815
  },
  {
    "id": "S9zcs6P5mn8",
    "slug": "why-i-shut-down-my-500k-online-pt-business-the-honest-story",
    "ep": 10,
    "title": "Why I Shut Down My £500K Online PT Business — The Honest Story",
    "date": "2025-08-29",
    "category": "business",
    "wordCount": 4621
  },
  {
    "id": "I1Yrhd9GZZU",
    "slug": "how-we-scaled-pt-launch-lab-courses-with-sam-merve-edtech",
    "ep": 9,
    "title": "How We Scaled PT Launch Lab Courses — with Sam, Merve EdTech",
    "date": "2025-08-13",
    "category": "business",
    "wordCount": 8455
  },
  {
    "id": "t8yzdFTxZss",
    "slug": "what-puregym-looks-for-when-hiring-personal-trainers-mac-livock",
    "ep": 8,
    "title": "What PureGym Looks for When Hiring Personal Trainers — Mac Livock",
    "date": "2025-08-08",
    "category": "industry",
    "wordCount": 7233
  },
  {
    "id": "brMSj4dfdBE",
    "slug": "is-becoming-a-personal-trainer-still-worth-it-the-honest-answer",
    "ep": 7,
    "title": "Is Becoming a Personal Trainer Still Worth It? The Honest Answer",
    "date": "2025-08-02",
    "category": "business",
    "wordCount": 5225
  },
  {
    "id": "1HK7woXEWhI",
    "slug": "how-i-built-an-online-pt-business-to-500k-ryans-full-story",
    "ep": 6,
    "title": "How I Built an Online PT Business to £500K — Ryan's Full Story",
    "date": "2025-07-25",
    "category": "business",
    "wordCount": 6955
  },
  {
    "id": "0rhp9fkBFsU",
    "slug": "sick-of-the-9-5-how-to-build-a-fitness-career-you-actually-want",
    "ep": null,
    "title": "Sick of the 9–5? How to Build a Fitness Career You Actually Want",
    "date": "2025-10-17",
    "category": "business",
    "wordCount": 842
  },
  {
    "id": "CDR39D_Esg8",
    "slug": "good-clients-vs-nightmare-clients-what-every-pt-needs-to-know",
    "ep": null,
    "title": "Good Clients vs Nightmare Clients — What Every PT Needs to Know",
    "date": "2025-07-05",
    "category": "business",
    "wordCount": 5301
  },
  {
    "id": "gqp9Grs1rF0",
    "slug": "will-ai-replace-personal-trainers-the-honest-answer",
    "ep": null,
    "title": "Will AI Replace Personal Trainers? The Honest Answer",
    "date": "2025-07-12",
    "category": "business",
    "wordCount": 3040
  },
  {
    "id": "LlPK2PzCrRA",
    "slug": "the-brutal-reality-of-a-personal-trainers-working-hours",
    "ep": null,
    "title": "The Brutal Reality of a Personal Trainer's Working Hours",
    "date": "2025-07-19",
    "category": "business",
    "wordCount": 175
  },
  {
    "id": "of0Zf6Jscgo",
    "slug": "why-most-fitness-influencers-are-lying-to-you",
    "ep": null,
    "title": "Why Most Fitness Influencers Are Lying to You",
    "date": "2025-07-19",
    "category": "industry",
    "wordCount": 6514
  }
];

export function getEpisodeIndex(slug: string): EpisodeIndex | undefined {
  return episodesIndex.find((e) => e.slug === slug);
}